### ISSUE TITLE
Ера және Ереке қарап кеттіңдер! 

### ISSUE THREAD

**Issue by Yertargyngo** [Yertargyngo/first_joint_development#1]
Бізге задача берілген бірге отырып, бір проект жасап, соған өзгеріс енгізу керек. Өзгеріс сендердің задачаларың Ера және Ереке. Кеттік ал!

**Comment by Yera-03** [comment]
Жақсы қарап кетеем!!!

**Comment by Yertargyngo** [comment]
Ереке келеді қазір

**Comment by Yertargyngo** [comment]
@Ereke-03 Қайдасың?

**Comment by Ereke-03** [comment]
Келдім міне!

**Comment by Yertargyngo** [comment]
1. Совместная разработка: несколько членов команды могут работать
над одним проектом, создавая, изменяя и сливая свои изменения в
единый репозиторий.
2. Обсуждение и управление задачами: члены команды могут
использовать функцию Issues на Github, чтобы создавать задачи,
назначать их на членов команды, обсуждать их и следить за их
выполнением.
3. Создание и слияние веток: команды могут использовать Git в Github,
чтобы создавать и управлять ветками, в которых каждый член
команды может работать над своей частью проекта, а затем
сливать изменения в основную ветку.
4. Управление доступом: в Github можно настраивать доступ к
репозиторию, чтобы разрешать или запрещать определенным членам
команды доступ к определенным файлам и папкам.
5. Научиться делать откат
6. Работать с командами git diff, git reset, git clean. Научится работать
и с другими командами.
7. Весь процесс необходимо делать в командной строке и стараться
довести до автомата.

**Comment by Yertargyngo** [comment]
Бір команда болып осы аяқтау кеерк боп тұр :)
